<x-filament-panels::page>
    @php($a=$analytics; $money=static fn($v)=>number_format((float)$v,0,',','.').' ₫')
    <div class="dth-analytics-shell" wire:loading.class="opacity-70">
        <div class="dth-analytics-toolbar"><div><div class="dth-analytics-toolbar__title">{{ __('analytics.campaign_analysis') }}</div><div class="dth-analytics-toolbar__subtitle">{{ __('analytics.campaign_analysis_subtitle') }}</div></div><div class="flex flex-wrap items-center gap-2"><x-analytics.period-filter /><x-filament::button wire:click="exportCsv" color="gray" icon="heroicon-o-arrow-down-tray">{{ __('uiux.dashboard.common.export_csv') }}</x-filament::button></div></div>

        <div class="dth-analytics-layout-2"><x-filament::section><x-slot name="heading">{{ __('analytics.attributed_revenue_trend') }}</x-slot><x-analytics.line-chart :current="$a['trend']['current']" :previous="$a['trend']['previous']" /></x-filament::section><x-filament::section><x-slot name="heading">{{ __('analytics.revenue_by_source') }}</x-slot><x-analytics.donut-chart :items="$a['sources']" :center-label="__('analytics.net_revenue')" /></x-filament::section></div>

        <div class="dth-analytics-layout-equal">
            <x-filament::section><x-slot name="heading">{{ __('analytics.campaign_efficiency') }}</x-slot><x-slot name="description">{{ __('analytics.campaign_efficiency_description') }}</x-slot><x-analytics.bar-chart :items="collect($a['marketing_campaigns'])->map(fn($r)=>['label'=>$r['name'],'value'=>$r['net_revenue'],'subtitle'=>'ROAS '.($r['roas']===null?'—':number_format($r['roas'],2).'x')])->all()" tone="marketing" /></x-filament::section>
            <x-filament::section><x-slot name="heading">{{ __('analytics.email_campaign_performance') }}</x-slot><x-slot name="description">{{ __('analytics.email_campaign_comparison_description') }}</x-slot><x-analytics.bar-chart :items="collect($a['email_campaigns'])->map(fn($r)=>['label'=>$r['name'],'value'=>$r['net_revenue'],'subtitle'=>number_format($r['open_rate'],1).'% · '.number_format($r['click_rate'],1).'%'])->all()" tone="info" /></x-filament::section>
        </div>

        <x-filament::section><x-slot name="heading">{{ __('analytics.marketing_campaign_comparison') }}</x-slot><x-slot name="description">{{ __('analytics.campaign_comparison_description') }}</x-slot><div class="overflow-x-auto"><table class="dth-analytics-table"><thead><tr><th>{{ __('field.name') }}</th><th class="numeric">{{ __('analytics.budget') }}</th><th class="numeric">{{ __('analytics.leads') }}</th><th class="numeric">{{ __('analytics.paid_customers') }}</th><th class="numeric">{{ __('analytics.conversion_rate') }}</th><th class="numeric">{{ __('analytics.net_revenue') }}</th><th class="numeric">ROAS</th></tr></thead><tbody>@forelse($a['marketing_campaigns'] as $row)<tr><td class="font-semibold">{{ $row['name'] }}</td><td class="numeric">{{ $money($row['budget']) }}</td><td class="numeric">{{ $row['leads'] }}</td><td class="numeric">{{ $row['paid_customers'] }}</td><td class="numeric">{{ number_format($row['conversion_rate'],1) }}%</td><td class="numeric font-semibold">{{ $money($row['net_revenue']) }}</td><td class="numeric"><x-filament::badge :color="($row['roas']??0)>=1?'success':'warning'">{{ $row['roas']===null?'—':number_format($row['roas'],2).'x' }}</x-filament::badge></td></tr>@empty<tr><td colspan="7" class="text-center text-gray-500">{{ __('uiux.dashboard.common.no_data') }}</td></tr>@endforelse</tbody></table></div></x-filament::section>

        <x-filament::section><x-slot name="heading">{{ __('analytics.email_campaign_comparison') }}</x-slot><x-slot name="description">{{ __('analytics.email_campaign_comparison_description') }}</x-slot><div class="overflow-x-auto"><table class="dth-analytics-table"><thead><tr><th>{{ __('field.name') }}</th><th class="numeric">{{ __('analytics.recipients') }}</th><th class="numeric">{{ __('analytics.open_rate') }}</th><th class="numeric">{{ __('analytics.click_rate') }}</th><th class="numeric">{{ __('analytics.paid_customers') }}</th><th class="numeric">{{ __('analytics.net_revenue') }}</th></tr></thead><tbody>@forelse($a['email_campaigns'] as $row)<tr><td class="font-semibold">{{ $row['name'] }}</td><td class="numeric">{{ $row['recipients'] }}</td><td class="numeric">{{ number_format($row['open_rate'],1) }}%</td><td class="numeric">{{ number_format($row['click_rate'],1) }}%</td><td class="numeric">{{ $row['paid_customers'] }}</td><td class="numeric font-semibold">{{ $money($row['net_revenue']) }}</td></tr>@empty<tr><td colspan="6" class="text-center text-gray-500">{{ __('uiux.dashboard.common.no_data') }}</td></tr>@endforelse</tbody></table></div></x-filament::section>

        <x-filament::section><x-slot name="heading">{{ __('analytics.landing_page_performance') }}</x-slot><div class="overflow-x-auto"><table class="dth-analytics-table"><thead><tr><th>{{ __('resource.landing_page.singular') }}</th><th class="numeric">{{ __('analytics.views') }}</th><th class="numeric">{{ __('analytics.submissions') }}</th><th class="numeric">{{ __('analytics.leads') }}</th><th class="numeric">{{ __('analytics.paid_customers') }}</th><th class="numeric">{{ __('analytics.net_revenue') }}</th></tr></thead><tbody>@forelse($a['landing_pages'] as $row)<tr><td class="font-semibold">{{ $row['name'] }}</td><td class="numeric">{{ $row['views'] }}</td><td class="numeric">{{ $row['submissions'] }}</td><td class="numeric">{{ $row['leads'] }}</td><td class="numeric">{{ $row['paid_customers'] }}</td><td class="numeric">{{ $money($row['net_revenue']) }}</td></tr>@empty<tr><td colspan="6" class="text-center text-gray-500">{{ __('uiux.dashboard.common.no_data') }}</td></tr>@endforelse</tbody></table></div></x-filament::section>
    </div>
</x-filament-panels::page>
