<?php
namespace Dth\Crm\Filament\Resources;
use Dth\Crm\Filament\Resources\ContactQualificationResource\Pages;
use Dth\Crm\Models\ContactQualification; use Dth\Crm\Filament\Navigation\CrmNavigationGroup; use Dth\Crm\Support\StatusColor; use Dth\Crm\Services\QualificationService; use Filament\Resources\Resource; use Filament\Schemas\Schema; use Filament\Schemas\Components\Section; use Filament\Forms\Components\{TextInput,Select,Textarea,DateTimePicker}; use Filament\Tables\Table; use Filament\Tables\Columns\TextColumn; use Filament\Tables\Filters\SelectFilter; use Filament\Actions; use Filament\Notifications\Notification;
class ContactQualificationResource extends Resource {protected static ?string $model=ContactQualification::class;protected static string|\BackedEnum|null $navigationIcon='heroicon-o-clipboard-document-check';protected static string|\UnitEnum|null $navigationGroup=CrmNavigationGroup::Crm;public static function getNavigationLabel():string{return \Dth\Crm\Support\UiText::get('navigation.qualifications','Lead qualification',context:'navigation');} public static function canCreate():bool{return false;}
 public static function form(Schema $schema):Schema{return $schema->components([Section::make('Đánh giá Lead')->schema([Select::make('status')->options(\Dth\Crm\Enums\QualificationStatus::options())->disabled(),Select::make('priority')->options(['low'=>'Thấp','normal'=>'Bình thường','high'=>'Cao','urgent'=>'Khẩn']),TextInput::make('score')->numeric()->minValue(0)->maxValue(100),TextInput::make('service_interest')->label('Dịch vụ quan tâm'),TextInput::make('budget_status')->label('Tình trạng ngân sách'),TextInput::make('budget_amount')->numeric()->label('Ngân sách'),TextInput::make('purchase_timeline')->label('Thời gian dự kiến mua'),TextInput::make('decision_role')->label('Vai trò quyết định'),DateTimePicker::make('next_follow_up_at')->label('Theo dõi tiếp'),Textarea::make('qualification_note')->label('Ghi chú')->columnSpanFull(),Textarea::make('unqualified_reason')->label('Lý do không đạt')->columnSpanFull()])->columns(2)]);}
 public static function table(Table $table):Table{return $table->columns([TextColumn::make('lead.lead_code')->label('Mã Lead')->searchable(),TextColumn::make('contact.display_name')->label('Liên hệ'),TextColumn::make('assignedStaff.name')->label('Phụ trách'),TextColumn::make('status')->badge()->color(fn($s)=>StatusColor::for($s)),TextColumn::make('priority')->badge(),TextColumn::make('score')->label('Điểm'),TextColumn::make('next_follow_up_at')->dateTime('d/m/Y H:i')])->filters([SelectFilter::make('status')->options(\Dth\Crm\Enums\QualificationStatus::options())])->recordActions([Actions\ActionGroup::make([self::transition('contacting','Bắt đầu liên hệ'),self::transition('follow_up','Theo dõi tiếp',true),self::transition('qualified','Đủ điều kiện'),self::transition('unqualified','Không đủ điều kiện'),self::transition('duplicate','Đánh dấu trùng'),self::transition('spam','Đánh dấu Spam'),self::transition('archived','Lưu trữ')]),Actions\ViewAction::make(),Actions\EditAction::make()])->defaultSort('id','desc');}
 private static function transition(string $to,string $label,bool $needDate=false):Actions\Action{$a=Actions\Action::make('to_'.$to)->label($label)->visible(fn(ContactQualification $r)=>$r->status!==$to)->form(array_values(array_filter([$needDate?DateTimePicker::make('next_follow_up_at')->required()->label('Theo dõi tiếp'):null,$to==='qualified'?TextInput::make('service_interest')->required()->label('Dịch vụ quan tâm'):null,$to==='unqualified'?Textarea::make('unqualified_reason')->required()->label('Lý do'):null])))->action(function(ContactQualification $r,array $d)use($to){app(QualificationService::class)->transition($r,$to,$d);Notification::make()->success()->title('Đã cập nhật trạng thái')->send();});return $a;}
 public static function getPages():array{return ['index'=>Pages\ListContactQualifications::route('/'),'view'=>Pages\ViewContactQualification::route('/{record}'),'edit'=>Pages\EditContactQualification::route('/{record}/edit')];}}
