<?php
namespace Dth\Crm\Filament\Resources;
use Dth\Crm\Filament\Resources\ContactResource\Pages;
use Dth\Crm\Models\Contact; use Dth\Crm\Filament\Navigation\CrmNavigationGroup; use Dth\Crm\Support\StatusColor; use Filament\Resources\Resource; use Filament\Schemas\Schema; use Filament\Schemas\Components\Section; use Filament\Forms\Components\{TextInput,Select,Textarea}; use Filament\Tables\Table; use Filament\Tables\Columns\TextColumn; use Filament\Actions;
class ContactResource extends Resource {protected static ?string $model=Contact::class; protected static string|\BackedEnum|null $navigationIcon='heroicon-o-user'; protected static string|\UnitEnum|null $navigationGroup=CrmNavigationGroup::Crm; public static function getNavigationLabel():string{return \Dth\Crm\Support\UiText::get('navigation.contacts','Contacts',context:'navigation');} public static function getModelLabel():string{return \Dth\Crm\Support\UiText::get('models.contact','Contact',context:'model');}
 public static function form(Schema $schema):Schema{return $schema->components([Section::make('Liên hệ')->schema([TextInput::make('contact_code')->label('Mã liên hệ'),Select::make('type')->label('Loại')->options(['personal'=>'Cá nhân','business'=>'Doanh nghiệp'])->native(false),TextInput::make('display_name')->label('Tên hiển thị'),TextInput::make('email')->label('Email'),TextInput::make('phone')->label('Điện thoại'),TextInput::make('source')->label('Nguồn')])->columns(2)->columnSpanFull()]);}
 public static function table(Table $table):Table{return $table->columns([TextColumn::make('contact_code')->label('Mã liên hệ')->searchable()->sortable(),TextColumn::make('type')->label('Loại')->searchable()->sortable()->badge()->color(fn($state)=>StatusColor::for($state)),TextColumn::make('display_name')->label('Tên')->searchable()->sortable(),TextColumn::make('email')->label('Email')->searchable()->sortable(),TextColumn::make('phone')->label('Điện thoại')->searchable()->sortable(),TextColumn::make('source')->label('Nguồn')->searchable()->sortable()])->recordActions([Actions\ViewAction::make(),Actions\EditAction::make(),Actions\DeleteAction::make()])->bulkActions([Actions\BulkActionGroup::make([Actions\DeleteBulkAction::make()->authorizeIndividualRecords()])])->defaultSort('id','desc');}
 public static function getPages():array{return ['index'=>Pages\ListContacts::route('/'),'create'=>Pages\CreateContact::route('/create'),'view'=>Pages\ViewContact::route('/{record}'),'edit'=>Pages\EditContact::route('/{record}/edit')];}
}
