<?php
namespace Dth\Crm\Filament\Resources;
use Dth\Crm\Filament\Resources\CustomerDistributionBatchResource\Pages;
use Dth\Crm\Models\CustomerDistributionBatch; use Dth\Crm\Filament\Navigation\CrmNavigationGroup; use Dth\Crm\Support\StatusColor; use Filament\Resources\Resource; use Filament\Schemas\Schema; use Filament\Schemas\Components\Section; use Filament\Forms\Components\{TextInput,Select,Textarea}; use Filament\Tables\Table; use Filament\Tables\Columns\TextColumn; use Filament\Actions;
class CustomerDistributionBatchResource extends Resource {protected static ?string $model=CustomerDistributionBatch::class; protected static string|\BackedEnum|null $navigationIcon='heroicon-o-arrows-right-left'; protected static string|\UnitEnum|null $navigationGroup=CrmNavigationGroup::Crm; public static function getNavigationLabel():string{return \Dth\Crm\Support\UiText::get('navigation.distribution','Customer distribution',context:'navigation');} public static function canCreate():bool{return true;} public static function getModelLabel():string{return \Dth\Crm\Support\UiText::get('models.distribution','Customer distribution',context:'model');}
 public static function form(Schema $schema):Schema{return $schema->components([Section::make('Phân phối khách hàng')->schema([TextInput::make('batch_code')->label('Mã đợt'),TextInput::make('batch_type')->label('Loại'),Select::make('strategy')->label('Chiến lược')->options(['round_robin'=>'Luân phiên','least_loaded'=>'Ít tải nhất','manual'=>'Thủ công'])->native(false),Select::make('status')->label('Trạng thái')->options(['draft'=>'Nháp','processing'=>'Đang xử lý','completed'=>'Hoàn tất','failed'=>'Lỗi'])->native(false)])->columns(2)->columnSpanFull()]);}
 public static function table(Table $table):Table{return $table->columns([TextColumn::make('batch_code')->label('Mã đợt')->searchable()->sortable(),TextColumn::make('strategy')->label('Chiến lược')->searchable()->sortable(),TextColumn::make('status')->label('Trạng thái')->searchable()->sortable()->badge()->formatStateUsing(fn($state):string=>\Dth\Crm\Support\UiText::status($state))->color(fn($state)=>StatusColor::for($state)),TextColumn::make('total_items')->label('Tổng')->searchable()->sortable(),TextColumn::make('processed_items')->label('Đã xử lý')->searchable()->sortable()])->recordActions([Actions\ViewAction::make(),Actions\EditAction::make(),Actions\DeleteAction::make()])->bulkActions([Actions\BulkActionGroup::make([Actions\DeleteBulkAction::make()->authorizeIndividualRecords()])])->defaultSort('id','desc');}
 public static function getPages():array{return ['index'=>Pages\ListCustomerDistributionBatchs::route('/'),'create'=>Pages\CreateCustomerDistributionBatch::route('/create'),'view'=>Pages\ViewCustomerDistributionBatch::route('/{record}'),'edit'=>Pages\EditCustomerDistributionBatch::route('/{record}/edit')];}
}
