<?php
namespace Dth\Crm\Filament\Resources;
use Dth\Crm\Filament\Resources\CustomerResource\Pages; use Dth\Crm\Filament\Resources\CustomerResource\RelationManagers\InteractionsRelationManager; use Dth\Crm\Filament\Resources\CustomerResource\RelationManagers\AssignmentsRelationManager;
use Dth\Crm\Models\Customer; use Dth\Crm\Filament\Navigation\CrmNavigationGroup; use Dth\Crm\Support\StatusColor; use Filament\Resources\Resource; use Filament\Schemas\Schema; use Filament\Schemas\Components\Section; use Filament\Forms\Components\{TextInput,Select,Textarea}; use Filament\Tables\Table; use Filament\Tables\Columns\TextColumn; use Filament\Actions;
class CustomerResource extends Resource {protected static ?string $model=Customer::class; protected static string|\BackedEnum|null $navigationIcon='heroicon-o-user-group'; protected static string|\UnitEnum|null $navigationGroup=CrmNavigationGroup::Crm; public static function getNavigationLabel():string{return \Dth\Crm\Support\UiText::get('navigation.customers','Customers',context:'navigation');} public static function getModelLabel():string{return \Dth\Crm\Support\UiText::get('models.customer','Customer',context:'model');}
 public static function form(Schema $schema):Schema{return $schema->components([Section::make('Khách hàng')->schema([TextInput::make('customer_code')->label('Mã KH'),Select::make('customer_type')->label('Loại')->options(['personal'=>'Cá nhân','business'=>'Doanh nghiệp'])->native(false),TextInput::make('display_name')->label('Tên'),TextInput::make('email')->label('Email'),TextInput::make('phone')->label('Điện thoại'),Select::make('status')->label('Trạng thái')->options(['potential'=>'Tiềm năng','active'=>'Hoạt động','inactive'=>'Không hoạt động','churned'=>'Rời bỏ'])->native(false),Select::make('priority')->label('Ưu tiên')->options(['low'=>'Thấp','normal'=>'Bình thường','high'=>'Cao','urgent'=>'Khẩn'])->native(false)])->columns(2)->columnSpanFull()]);}
 public static function table(Table $table):Table{return $table->columns([TextColumn::make('customer_code')->label('Mã KH')->searchable()->sortable(),TextColumn::make('display_name')->label('Khách hàng')->searchable()->sortable(),TextColumn::make('customer_type')->label('Loại')->searchable()->sortable(),TextColumn::make('status')->label('Trạng thái')->searchable()->sortable()->badge()->color(fn($state)=>StatusColor::for($state)),TextColumn::make('total_revenue')->label('Doanh thu')->searchable()->sortable()])->recordActions([Actions\ViewAction::make(),Actions\EditAction::make(),Actions\DeleteAction::make()])->bulkActions([Actions\BulkActionGroup::make([Actions\BulkAction::make('distribute')->label('Phân phối khách hàng')->icon('heroicon-o-arrows-right-left')->requiresConfirmation()->action(function($records){app(\Dth\Crm\Services\CustomerDistributionService::class)->distribute($records->modelKeys(),auth()->id());\Filament\Notifications\Notification::make()->success()->title('Đã phân phối khách hàng')->send();}),Actions\DeleteBulkAction::make()->authorizeIndividualRecords()])])->defaultSort('id','desc');}
 public static function getPages():array{return ['index'=>Pages\ListCustomers::route('/'),'create'=>Pages\CreateCustomer::route('/create'),'view'=>Pages\ViewCustomer::route('/{record}'),'edit'=>Pages\EditCustomer::route('/{record}/edit')];}
 public static function getRelations():array{return [InteractionsRelationManager::class,AssignmentsRelationManager::class];}
}
