<?php
namespace Dth\Crm\Filament\Resources;
use Dth\Crm\Filament\Resources\StaffResource\Pages; use Dth\Crm\Filament\Resources\StaffResource\RelationManagers\AvailabilitiesRelationManager;
use Dth\Crm\Models\Staff; use Dth\Crm\Filament\Navigation\CrmNavigationGroup; use Dth\Crm\Support\StatusColor; use Filament\Resources\Resource; use Filament\Schemas\Schema; use Filament\Schemas\Components\Section; use Filament\Forms\Components\{TextInput,Select,Textarea}; use Filament\Tables\Table; use Filament\Tables\Columns\TextColumn; use Filament\Actions;
class StaffResource extends Resource {protected static ?string $model=Staff::class; protected static string|\BackedEnum|null $navigationIcon='heroicon-o-identification'; protected static string|\UnitEnum|null $navigationGroup=CrmNavigationGroup::Crm; public static function getNavigationLabel():string{return \Dth\Crm\Support\UiText::get('navigation.staff','CRM staff',context:'navigation');} public static function getModelLabel():string{return \Dth\Crm\Support\UiText::get('models.staff','CRM staff',context:'model');}
 public static function form(Schema $schema):Schema{return $schema->components([Section::make('Nhân viên CRM')->schema([TextInput::make('staff_code')->label('Mã NV'),TextInput::make('name')->label('Tên'),TextInput::make('email')->label('Email'),TextInput::make('phone')->label('Điện thoại'),TextInput::make('department')->label('Phòng ban'),TextInput::make('position')->label('Chức vụ'),Select::make('employment_status')->label('Trạng thái')->options(['active'=>'Hoạt động','inactive'=>'Ngừng hoạt động','resigned'=>'Đã nghỉ'])->native(false),TextInput::make('lead_capacity')->label('Sức chứa Lead'),TextInput::make('customer_capacity')->label('Sức chứa Khách hàng'),TextInput::make('distribution_weight')->label('Trọng số phân phối')])->columns(2)->columnSpanFull()]);}
 public static function table(Table $table):Table{return $table->columns([TextColumn::make('staff_code')->label('Mã NV')->searchable()->sortable(),TextColumn::make('name')->label('Nhân viên')->searchable()->sortable(),TextColumn::make('department')->label('Phòng ban')->searchable()->sortable(),TextColumn::make('position')->label('Chức vụ')->searchable()->sortable(),TextColumn::make('employment_status')->label('Trạng thái')->searchable()->sortable()->badge()->formatStateUsing(fn($state):string=>\Dth\Crm\Support\UiText::status($state))->color(fn($state)=>StatusColor::for($state))])->recordActions([Actions\ViewAction::make(),Actions\EditAction::make(),Actions\DeleteAction::make()])->bulkActions([Actions\BulkActionGroup::make([Actions\DeleteBulkAction::make()->authorizeIndividualRecords()])])->defaultSort('id','desc');}
 public static function getPages():array{return ['index'=>Pages\ListStaffs::route('/'),'create'=>Pages\CreateStaff::route('/create'),'view'=>Pages\ViewStaff::route('/{record}'),'edit'=>Pages\EditStaff::route('/{record}/edit')];}
 public static function getRelations():array{return [AvailabilitiesRelationManager::class];}
}
