<?php

return [
    'default' => env('APP_LOCALE', 'en'),
    'fallback' => env('APP_FALLBACK_LOCALE', 'en'),

    'supported' => [
        'en' => [
            'label' => 'English',
            'native' => 'English',
        ],
        'vi' => [
            'label' => 'Vietnamese',
            'native' => 'Tiếng Việt',
        ],
    ],

    // When a module requests a key that has no translation in the current
    // locale, store it once in system_translations. A later admin/AI workflow
    // can fill the missing value without changing the module code.
    'capture_missing' => env('UI_TRANSLATION_CAPTURE_MISSING', true),

    // Central root-level translations. Modules provide a stable key and a
    // canonical default string; locale-specific overrides live here or in DB.
    'translations' => [
        'vi' => [
            'common' => [
                'actions' => [
                    'new' => 'Mới',
                    'save' => 'Lưu',
                    'cancel' => 'Hủy',
                    'delete' => 'Xóa',
                    'edit' => 'Sửa',
                    'view' => 'Xem',
                    'add' => 'Thêm',
                    'close' => 'Đóng',
                    'import' => 'Nhập',
                    'send' => 'Gửi',
                    'schedule' => 'Lên lịch',
                    'unschedule' => 'Bỏ lịch',
                    'release' => 'Gỡ chặn',
                    'verify' => 'Xác minh',
                    'test' => 'Kiểm tra',
                ],
                'fields' => [
                    'name' => 'Tên',
                    'status' => 'Trạng thái',
                    'description' => 'Mô tả',
                    'notes' => 'Ghi chú',
                    'email' => 'Email',
                    'source' => 'Nguồn',
                    'reason' => 'Lý do',
                    'time' => 'Thời gian',
                ],
                'statuses' => [
                    'draft' => 'Bản nháp',
                    'scheduled' => 'Đã lên lịch',
                    'processing' => 'Đang xử lý',
                    'completed' => 'Hoàn tất',
                    'cancelled' => 'Đã hủy',
                    'failed' => 'Thất bại',
                    'pending' => 'Đang chờ',
                    'queued' => 'Đang xếp hàng',
                    'sending' => 'Đang gửi',
                    'sent' => 'Đã gửi',
                    'delivered' => 'Đã chuyển phát',
                    'opened' => 'Đã mở',
                    'clicked' => 'Đã nhấp',
                    'unsubscribed' => 'Đã hủy đăng ký',
                    'bounced' => 'Bị trả lại',
                    'complained' => 'Bị khiếu nại',
                    'suppressed' => 'Bị chặn',
                    'active' => 'Hoạt động',
                    'inactive' => 'Không hoạt động',
                    'error' => 'Lỗi',
                    'verified' => 'Đã xác minh',
                    'disabled' => 'Đã tắt',
                    'success' => 'Thành công',
                    'manual' => 'Thủ công',
                    'unsubscribe' => 'Hủy đăng ký',
                    'complaint' => 'Khiếu nại',
                    'bounce' => 'Trả lại',
                    'released' => 'Đã gỡ chặn',
                    'subscribed' => 'Đã đăng ký',
                ],
            ],
            'email' => [
                'navigation' => [
                    'group' => 'Email',
                    'dashboard' => 'Tổng quan Email',
                    'sending_domains' => 'Tên miền gửi',
                    'sending_accounts' => 'Tài khoản gửi',
                    'template_categories' => 'Danh mục mẫu',
                    'templates' => 'Mẫu Email',
                    'campaigns' => 'Chiến dịch',
                    'delivery_log' => 'Nhật ký gửi',
                    'suppressions' => 'Danh sách chặn',
                ],
                'dashboard' => [
                    'title' => 'Phân tích Email',
                    'subheading' => 'Hiệu suất từ :start đến :end',
                    'filters' => [
                        'action' => 'Bộ lọc',
                        'heading' => 'Bộ lọc báo cáo',
                        'apply' => 'Áp dụng bộ lọc',
                        'start_date' => 'Từ ngày',
                        'end_date' => 'Đến ngày',
                        'sending_account' => 'Tài khoản gửi',
                        'all_accounts' => 'Tất cả tài khoản gửi',
                        'campaign_status' => 'Trạng thái chiến dịch',
                        'all_statuses' => 'Tất cả trạng thái',
                        'compare_previous' => 'So sánh kỳ trước',
                        'compare_yes' => 'Có',
                        'compare_no' => 'Không',
                        'reset' => 'Đặt lại',
                        'range_label' => 'Khoảng báo cáo',
                        'presets' => [
                            '7d' => '7 ngày',
                            '30d' => '30 ngày',
                            '90d' => '90 ngày',
                            'month' => 'Tháng này',
                        ],
                    ],
                    'delta' => [
                        'unavailable' => 'Chưa có dữ liệu so sánh',
                        'compared_previous' => ':change so với kỳ trước',
                    ],
                    'empty' => [
                        'heading' => 'Không có dữ liệu trong giai đoạn này',
                        'description' => 'Hãy thử giai đoạn khác hoặc bỏ bớt bộ lọc Dashboard.',
                    ],
                    'metrics' => [
                        'campaigns' => 'Chiến dịch',
                        'recipients' => 'Người nhận',
                        'sent' => 'Đã gửi',
                        'open_rate' => 'Tỷ lệ mở',
                        'click_rate' => 'Tỷ lệ nhấp',
                        'ctor' => 'Tỷ lệ nhấp trên mở',
                        'unsubscribe_rate' => 'Tỷ lệ hủy đăng ký',
                        'failure_rate' => 'Tỷ lệ thất bại',
                        'unique_opens' => 'Lượt mở duy nhất',
                        'unique_clicks' => 'Lượt nhấp duy nhất',
                        'opened' => 'Đã mở',
                        'clicked' => 'Đã nhấp',
                        'total_clicks' => 'Tổng lượt nhấp',
                        'unique_clickers' => 'Người nhấp duy nhất',
                    ],
                    'charts' => [
                        'performance_trend' => 'Hiệu suất Email theo thời gian',
                        'performance_trend_description' => 'Số email gửi, lượt mở duy nhất và lượt nhấp duy nhất theo ngày hoạt động.',
                        'engagement_funnel' => 'Phễu tương tác',
                        'engagement_funnel_description' => 'Mức chuyển đổi từ người nhận sang các hành vi tương tác có ý nghĩa.',
                        'audience' => 'Tập người nhận',
                        'top_campaigns' => 'Chiến dịch hiệu quả nhất',
                        'top_campaigns_description' => 'Xếp hạng theo tỷ lệ nhấp, kèm tỷ lệ mở để đối chiếu.',
                        'top_links' => 'Liên kết được nhấp nhiều nhất',
                        'top_links_description' => 'Các đích được theo dõi có tương tác cao nhất trong giai đoạn đã chọn.',
                        'account_performance' => 'Hiệu suất theo tài khoản gửi',
                        'account_performance_description' => 'Tỷ lệ mở và nhấp theo từng tài khoản gửi trong giai đoạn đã chọn.',
                        'rate_percent' => 'Tỷ lệ (%)',
                    ],
                    'infrastructure' => [
                        'heading' => 'Hạ tầng Email',
                        'description' => 'Tình trạng sẵn sàng cơ bản. Theo dõi heartbeat của worker sẽ được bổ sung ở Bước I.',
                        'accounts' => 'Tài khoản gửi',
                        'account_errors' => ':count tài khoản đang lỗi',
                        'domains' => 'Tên miền đã xác minh',
                        'domain_errors' => ':count tên miền xác minh thất bại',
                        'pending_jobs' => 'Job Email đang chờ',
                        'queue_note' => 'Số job đang chờ trong hàng đợi Email đã cấu hình.',
                        'failed_jobs' => 'Job thất bại',
                        'failed_jobs_note' => 'Các job hàng đợi thất bại cần được vận hành kiểm tra.',
                    ],
                ],
                'models' => [
                    'sending_domain' => 'Tên miền gửi',
                    'sending_domains' => 'Tên miền gửi',
                    'sending_account' => 'Tài khoản gửi',
                    'sending_accounts' => 'Tài khoản gửi',
                    'template_category' => 'Danh mục mẫu',
                    'template_categories' => 'Danh mục mẫu',
                    'template' => 'Mẫu Email',
                    'templates' => 'Mẫu Email',
                    'campaign' => 'Chiến dịch',
                    'campaigns' => 'Chiến dịch',
                    'delivery_message' => 'Email đã gửi',
                    'delivery_messages' => 'Nhật ký gửi',
                    'suppression' => 'Địa chỉ chặn',
                    'suppressions' => 'Danh sách chặn',
                ],
                'domain' => [
                    'section' => 'Xác minh tên miền',
                    'section_description' => 'Cấu hình tên miền người gửi và DKIM selector tùy chọn để xác minh DNS.',
                    'domain' => 'Tên miền',
                    'dkim_selector' => 'DKIM selector',
                    'notes' => 'Ghi chú',
                    'domain_help' => 'Chỉ nhập tên miền. Không bao gồm http://, https://, đường dẫn hoặc dấu / ở cuối.',
                    'dkim_help' => 'Selector dùng để kiểm tra selector._domainkey.domain. Để trống nếu DKIM chưa được cấu hình.',
                    'last_checked' => 'Kiểm tra gần nhất',
                    'verify' => 'Xác minh',
                    'verified_title' => 'Tên miền đã được xác minh',
                    'incomplete_title' => 'Xác minh chưa hoàn tất',
                    'verification_body' => 'SPF: :spf; DKIM: :dkim; DMARC: :dmarc',
                ],
                'account' => [
                    'identity' => 'Danh tính gửi',
                    'domain' => 'Tên miền',
                    'from_name' => 'Tên người gửi',
                    'from_email' => 'Email người gửi',
                    'reply_to' => 'Reply-to',
                    'host' => 'Host',
                    'port' => 'Cổng',
                    'security' => 'Bảo mật',
                    'timeout' => 'Thời gian chờ',
                    'username' => 'Tên đăng nhập',
                    'password' => 'Mật khẩu',
                    'local_domain' => 'Tên miền cục bộ',
                    'limits' => 'Giới hạn gửi',
                    'limits_description' => 'Giới hạn an toàn tùy chọn. Để trống nếu nhà cung cấp SMTP tự quản lý giới hạn.',
                    'hourly_limit' => 'Giới hạn mỗi giờ',
                    'daily_limit' => 'Giới hạn mỗi ngày',
                    'last_test' => 'Lần kiểm tra gần nhất',
                    'recipient_email' => 'Email người nhận',
                    'recipient_name' => 'Tên người nhận',
                    'smtp_security_help' => 'Dùng SMTP / STARTTLS cho cổng như 587. Dùng SMTPS khi nhà cung cấp yêu cầu TLS ngầm định, thường là cổng 465.',
                    'password_help' => 'Thông tin đăng nhập được mã hóa trước khi lưu. Khi sửa, để trống để giữ mật khẩu hiện tại.',
                    'local_domain_help' => 'Tên miền EHLO/HELO tùy chọn. Để trống trừ khi nhà cung cấp SMTP yêu cầu.',
                    'test_sent' => 'Đã gửi email kiểm tra SMTP',
                    'test_failed' => 'Kiểm tra SMTP thất bại',
                ],
                'template_category' => [
                    'category' => 'Danh mục',
                    'active' => 'Hoạt động',
                    'description' => 'Mô tả',
                    'system_slug' => 'Slug hệ thống',
                    'templates' => 'Mẫu Email',
                ],
                'variables' => [
                    'recipient_name' => 'Tên người nhận',
                    'recipient_name_description' => 'Tên được lưu trên người nhận của chiến dịch.',
                    'recipient_email' => 'Email người nhận',
                    'recipient_email_description' => 'Địa chỉ email của người nhận chiến dịch.',
                    'recipient_name_nested' => 'Tên người nhận (nested)',
                    'recipient_name_nested_description' => 'Alias của tên người nhận.',
                    'recipient_email_nested' => 'Email người nhận (nested)',
                    'recipient_email_nested_description' => 'Alias của địa chỉ email người nhận.',
                    'customer_name' => 'Tên khách hàng',
                    'customer_name_description' => 'Tên hiển thị của khách hàng/người nhận.',
                    'customer_email' => 'Email khách hàng',
                    'customer_email_description' => 'Địa chỉ email của khách hàng/người nhận.',
                    'unsubscribe_link' => 'Liên kết hủy đăng ký',
                    'unsubscribe_link_description' => 'URL hủy đăng ký duy nhất cho từng người nhận. Hệ thống tự thêm footer tuân thủ nếu biến này không có trong nội dung.',
                    'custom_description' => 'Giá trị cá nhân hóa tùy chỉnh. Hãy cung cấp giá trị này cho từng người nhận thủ công hoặc qua cột CSV cùng tên.',
                    'help_intro' => 'Dùng các biến này trong những trường được hỗ trợ. Hệ thống sẽ thay thế chúng cho từng người nhận khi chiến dịch được gửi.',
                ],
                'preview' => [
                    'missing_variables' => 'Thiếu biến xem trước:',
                    'subject' => 'Tiêu đề',
                    'preheader' => 'Preheader',
                    'html_preview' => 'Xem trước HTML',
                    'plain_text' => 'Văn bản thuần',
                ],
                'template' => [
                    'basic_information' => 'Thông tin cơ bản',
                    'category' => 'Danh mục',
                    'status' => 'Trạng thái',
                    'description' => 'Mô tả',
                    'content' => 'Nội dung',
                    'content_description' => 'Thiết kế email trực quan, dán nội dung hoặc nhập tệp HTML có sẵn. Có thể chèn biến cá nhân hóa từ giao diện.',
                    'subject' => 'Tiêu đề',
                    'subject_help' => 'Dùng nút biến để chèn placeholder được hỗ trợ. Biến tùy chỉnh phát hiện từ HTML nhập vào sẽ được giữ lại.',
                    'preheader' => 'Preheader',
                    'preheader_help' => 'Nội dung xem trước tùy chọn mà nhiều ứng dụng email hiển thị cạnh hoặc dưới tiêu đề.',
                    'import_html' => 'Nhập HTML',
                    'import_help' => 'Tải lên tệp .html tối đa 2 MB. Các biến có dạng {{ variable }} sẽ được giữ nguyên và tự động nhận diện.',
                    'imported_title' => 'Đã nhập HTML',
                    'imported_body' => 'Các placeholder {{ variable }} trong tệp đã được giữ nguyên. Hãy kiểm tra các biến được nhận diện trước khi lưu.',
                    'import_failed' => 'Nhập HTML thất bại',
                    'email_body' => 'Nội dung email',
                    'body_help' => 'Dùng công cụ merge-tag để chèn biến cá nhân hóa có sẵn. Biến tùy chỉnh trong HTML nhập vào vẫn được hỗ trợ.',
                    'read_variables' => 'Xem hướng dẫn biến cá nhân hóa',
                    'variables_heading' => 'Biến cá nhân hóa',
                    'insert_variable' => 'Chèn biến cá nhân hóa',
                    'variable' => 'Biến',
                    'system_key' => 'Khóa hệ thống',
                    'preview' => 'Xem trước',
                    'preview_title' => 'Xem trước: :name',
                ],
                'campaign' => [
                    'section' => 'Chiến dịch',
                    'name' => 'Tên',
                    'sending_account' => 'Tài khoản gửi',
                    'template' => 'Mẫu Email',
                    'template_help' => 'Nội dung mẫu được sao chép vào chiến dịch. Sửa chiến dịch sẽ không làm thay đổi mẫu gốc.',
                    'content' => 'Nội dung',
                    'content_description' => 'Nội dung chiến dịch bị khóa khi rời trạng thái Bản nháp. Các biến được kiểm tra với dữ liệu người nhận trước khi Gửi hoặc Lên lịch.',
                    'subject' => 'Tiêu đề',
                    'preheader' => 'Preheader',
                    'email_body' => 'Nội dung email',
                    'body_help' => 'Dùng công cụ merge-tag để chèn biến có sẵn. Biến tùy chỉnh từ mẫu nhập vào vẫn được nhận diện.',
                    'insert_variable' => 'Chèn biến cá nhân hóa',
                    'variable' => 'Biến',
                    'campaign_column' => 'Chiến dịch',
                    'account' => 'Tài khoản',
                    'recipients' => 'Người nhận',
                    'scheduled' => 'Đã lên lịch',
                    'completed' => 'Hoàn tất',
                    'send' => 'Gửi',
                    'queued_title' => 'Chiến dịch đã được đưa vào hàng đợi',
                    'cannot_send' => 'Không thể gửi chiến dịch',
                    'schedule' => 'Lên lịch',
                    'send_at' => 'Gửi lúc',
                    'scheduled_title' => 'Đã lên lịch chiến dịch',
                    'cannot_schedule' => 'Không thể lên lịch chiến dịch',
                    'unschedule' => 'Bỏ lịch',
                    'returned_draft' => 'Chiến dịch đã trở về Bản nháp',
                    'delete' => 'Xóa',
                ],
                'recipient' => [
                    'title' => 'Người nhận',
                    'email' => 'Email',
                    'name' => 'Tên',
                    'sent' => 'Đã gửi',
                    'opened' => 'Đã mở',
                    'clicked' => 'Đã nhấp',
                    'add' => 'Thêm',
                    'import' => 'Nhập',
                    'csv_file' => 'Tệp CSV',
                    'expected_columns' => 'Các cột dự kiến: :columns. Những dòng thiếu dữ liệu cá nhân hóa bắt buộc sẽ bị bỏ qua.',
                    'invalid_csv' => 'Tệp CSV không hợp lệ.',
                    'imported_title' => 'Đã nhập người nhận',
                    'imported_summary' => 'Thêm: :added · Cập nhật: :updated · Không hợp lệ/thiếu dữ liệu: :invalid',
                    'import_failed' => 'Nhập người nhận thất bại',
                    'cannot_delete' => 'Không thể xóa người nhận',
                    'frozen' => 'Danh sách người nhận bị khóa sau khi chiến dịch rời trạng thái Bản nháp.',
                    'required_variable' => 'Bắt buộc bởi {{ :variable }} trong nội dung chiến dịch.',
                ],
                'analytics' => [
                    'recipients' => 'Người nhận',
                    'recipients_description' => 'Đang chờ :pending · Đang xếp hàng :queued',
                    'sent' => 'Đã gửi',
                    'sent_description' => 'Thất bại :failed · Bị chặn :suppressed',
                    'delivered' => 'Đã chuyển phát',
                    'delivery_rate' => ':rate% trên số đã gửi',
                    'not_available' => 'Không khả dụng',
                    'delivery_unavailable' => 'Transport hiện tại không cung cấp xác nhận chuyển phát.',
                    'opened' => 'Đã mở',
                    'open_rate' => 'Tỷ lệ mở :rate%',
                    'clicked' => 'Đã nhấp',
                    'click_rate' => 'Tỷ lệ nhấp :rate%',
                    'unsubscribed' => 'Hủy đăng ký từ chiến dịch',
                    'unsubscribe_rate' => 'Tỷ lệ hủy đăng ký lịch sử :rate%',
                ],
                'delivery' => [
                    'recipient' => 'Người nhận',
                    'campaign' => 'Chiến dịch',
                    'account' => 'Tài khoản',
                    'opens' => 'Lượt mở',
                    'clicks' => 'Lượt nhấp',
                    'sent' => 'Đã gửi',
                    'sending_account' => 'Tài khoản gửi',
                    'message' => 'Email',
                    'name' => 'Tên',
                    'from' => 'Từ',
                    'provider_id' => 'Provider ID',
                    'failure' => 'Lỗi',
                    'event_timeline' => 'Dòng thời gian sự kiện',
                    'event' => 'Sự kiện',
                    'time' => 'Thời gian',
                    'provider_event' => 'Sự kiện nhà cung cấp',
                ],
                'suppression' => [
                    'section' => 'Danh sách chặn',
                    'status' => 'Trạng thái',
                    'added' => 'Đã thêm',
                    'released' => 'Đã gỡ',
                    'release_source' => 'Nguồn gỡ chặn',
                    'release_note' => 'Ghi chú gỡ chặn',
                    'manual' => 'Thủ công',
                    'unsubscribe' => 'Hủy đăng ký',
                    'bounce' => 'Trả lại',
                    'complaint' => 'Khiếu nại',
                    'resubscribe' => 'Đăng ký lại',
                    'release' => 'Gỡ chặn',
                    'resubscribe_description' => 'Thao tác này chỉ thay đổi trạng thái đăng ký hiện tại. Chiến dịch gốc vẫn giữ chỉ số Hủy đăng ký lịch sử.',
                    'release_description' => 'Gỡ chặn thủ công nhưng vẫn giữ lịch sử kiểm toán?',
                    'reason_source' => 'Lý do / nguồn',
                    'customer_opt_in' => 'Khách hàng đồng ý nhận lại',
                    'customer_request' => 'Khách hàng yêu cầu đăng ký lại',
                    'admin_correction' => 'Điều chỉnh quản trị',
                    'other' => 'Khác',
                    'note_evidence' => 'Ghi chú / bằng chứng',
                    'resubscribed_title' => 'Địa chỉ đã được đăng ký lại cho các chiến dịch tương lai',
                    'released_title' => 'Đã gỡ chặn',
                    'history_unchanged' => 'Chỉ số lịch sử của chiến dịch không thay đổi.',
                ],
            ],
        ],
    ],
];
