<?php
use Illuminate\Database\Migrations\Migration; use Illuminate\Database\Schema\Blueprint; use Illuminate\Support\Facades\Schema;
return new class extends Migration {
 public function up():void {
  // CRM only owns CRM-agent settings. Employee identity/organization is owned by Human Resource.
  // The legacy physical table name crm_staff is retained to preserve assignment foreign-key IDs.
  Schema::create('crm_staff', function(Blueprint $t){$t->id();$t->foreignId('employee_id')->unique()->constrained('hr_employees')->restrictOnDelete();$t->boolean('assignment_enabled')->default(true)->index();$t->unsignedInteger('lead_capacity')->default(50);$t->unsignedInteger('customer_capacity')->nullable();$t->decimal('distribution_weight',8,2)->default(1);$t->timestamps();$t->softDeletes();});
  Schema::create('crm_contacts', function(Blueprint $t){$t->id();$t->string('contact_code')->unique();$t->string('type',20)->index();$t->string('display_name');$t->string('email')->nullable();$t->string('normalized_email')->nullable()->index();$t->string('phone',30)->nullable();$t->string('normalized_phone',30)->nullable()->index();$t->string('source')->nullable()->index();$t->json('tags')->nullable();$t->json('metadata')->nullable();$t->timestamps();$t->softDeletes();});
  Schema::create('crm_companies', function(Blueprint $t){$t->id();$t->string('company_code')->unique();$t->string('legal_name');$t->string('normalized_name')->index();$t->string('tax_code',30)->nullable()->unique();$t->string('email_domain')->nullable()->index();$t->string('website')->nullable();$t->string('phone',30)->nullable();$t->string('normalized_phone',30)->nullable()->index();$t->string('industry')->nullable();$t->string('address',500)->nullable();$t->string('province',100)->nullable();$t->string('country_code',3)->default('VN');$t->string('lifecycle_stage',30)->default('prospect')->index();$t->foreignId('account_owner_staff_id')->nullable()->constrained('crm_staff')->nullOnDelete();$t->string('source_submission_reference')->nullable()->index();$t->json('metadata')->nullable();$t->timestamps();$t->softDeletes();});
  Schema::create('crm_personal_contact_profiles', function(Blueprint $t){$t->id();$t->foreignId('contact_id')->unique()->constrained('crm_contacts')->cascadeOnDelete();$t->string('first_name')->nullable();$t->string('last_name')->nullable();$t->date('date_of_birth')->nullable();$t->string('gender',30)->nullable();$t->string('identity_number',50)->nullable();$t->string('address_line')->nullable();$t->string('ward',100)->nullable();$t->string('district',100)->nullable();$t->string('province',100)->nullable();$t->string('country',100)->default('Vietnam');$t->string('occupation',150)->nullable();$t->string('service_interest')->nullable();$t->decimal('expected_budget',18,2)->nullable();$t->json('metadata')->nullable();$t->timestamps();});
  Schema::create('crm_business_contact_profiles', function(Blueprint $t){$t->id();$t->foreignId('contact_id')->unique()->constrained('crm_contacts')->cascadeOnDelete();$t->foreignId('company_id')->nullable()->constrained('crm_companies')->nullOnDelete();$t->string('company_name');$t->string('tax_code',30)->nullable()->index();$t->string('company_address',500)->nullable();$t->string('legal_representative')->nullable();$t->string('contact_position',150)->nullable();$t->string('business_email')->nullable();$t->string('business_phone',30)->nullable();$t->string('industry',150)->nullable();$t->string('tax_verification_status',30)->default('pending');$t->json('tax_verification_data')->nullable();$t->timestamps();});
  Schema::create('crm_company_contacts', function(Blueprint $t){$t->id();$t->foreignId('company_id')->constrained('crm_companies')->cascadeOnDelete();$t->foreignId('contact_id')->constrained('crm_contacts')->cascadeOnDelete();$t->string('job_title')->nullable();$t->string('department')->nullable();$t->string('decision_role',50)->nullable();$t->boolean('is_primary')->default(false);$t->boolean('is_active')->default(true);$t->timestamps();$t->unique(['company_id','contact_id']);});
  Schema::create('crm_company_match_candidates', function(Blueprint $t){$t->id();$t->string('submission_reference')->nullable()->index();$t->foreignId('contact_id')->nullable()->constrained('crm_contacts')->cascadeOnDelete();$t->foreignId('suggested_company_id')->constrained('crm_companies')->cascadeOnDelete();$t->unsignedTinyInteger('confidence')->default(0);$t->string('matched_by',50);$t->string('status',30)->default('pending')->index();$t->foreignId('reviewed_by_user_id')->nullable()->constrained('users')->nullOnDelete();$t->timestamp('reviewed_at')->nullable();$t->timestamps();});
  Schema::create('crm_company_assignments', function(Blueprint $t){$t->id();$t->foreignId('company_id')->constrained('crm_companies')->cascadeOnDelete();$t->foreignId('staff_id')->constrained('crm_staff')->cascadeOnDelete();$t->string('assignment_type',30)->default('owner');$t->string('status',30)->default('active')->index();$t->text('reason')->nullable();$t->foreignId('assigned_by_user_id')->nullable()->constrained('users')->nullOnDelete();$t->timestamp('starts_at')->nullable();$t->timestamp('ends_at')->nullable();$t->timestamps();});
  Schema::create('crm_leads', function(Blueprint $t){$t->id();$t->string('lead_code')->unique();$t->string('submission_reference')->nullable()->index();$t->foreignId('contact_id')->nullable()->constrained('crm_contacts')->nullOnDelete();$t->foreignId('company_id')->nullable()->constrained('crm_companies')->nullOnDelete();$t->foreignId('assigned_staff_id')->nullable()->constrained('crm_staff')->nullOnDelete();$t->string('source')->nullable()->index();$t->string('source_detail')->nullable();$t->string('title')->nullable();$t->string('service_interest')->nullable()->index();$t->string('service_reference')->nullable()->index();$t->decimal('estimated_value',18,2)->nullable();$t->string('intake_status',40)->default('new')->index();$t->timestamp('assigned_at')->nullable();$t->foreignId('assigned_by_user_id')->nullable()->constrained('users')->nullOnDelete();$t->timestamp('converted_to_opportunity_at')->nullable();$t->string('sales_opportunity_reference')->nullable()->index();$t->json('attribution')->nullable();$t->json('form_answers')->nullable();$t->json('metadata')->nullable();$t->timestamps();$t->softDeletes();});
  Schema::create('crm_contact_qualifications', function(Blueprint $t){$t->id();$t->foreignId('lead_id')->unique()->constrained('crm_leads')->cascadeOnDelete();$t->foreignId('contact_id')->nullable()->constrained('crm_contacts')->nullOnDelete();$t->foreignId('assigned_staff_id')->nullable()->constrained('crm_staff')->nullOnDelete();$t->string('status',30)->default('new')->index();$t->string('priority',20)->default('normal')->index();$t->unsignedTinyInteger('score')->default(0);$t->string('qualification_result',50)->nullable();$t->string('service_interest')->nullable();$t->decimal('estimated_value',18,2)->nullable();$t->string('budget_status',30)->nullable();$t->decimal('budget_amount',18,2)->nullable();$t->string('purchase_timeline',30)->nullable();$t->string('decision_role',50)->nullable();$t->text('qualification_note')->nullable();$t->timestamp('first_contacted_at')->nullable();$t->timestamp('last_contacted_at')->nullable();$t->timestamp('next_follow_up_at')->nullable();$t->timestamp('qualified_at')->nullable();$t->foreignId('qualified_by_staff_id')->nullable()->constrained('crm_staff')->nullOnDelete();$t->text('unqualified_reason')->nullable();$t->timestamp('converted_at')->nullable();$t->timestamps();});
  Schema::create('crm_qualification_notes', function(Blueprint $t){$t->id();$t->foreignId('qualification_id')->constrained('crm_contact_qualifications')->cascadeOnDelete();$t->foreignId('staff_id')->nullable()->constrained('crm_staff')->nullOnDelete();$t->text('note');$t->timestamps();});
  Schema::create('crm_lead_activities', function(Blueprint $t){$t->id();$t->foreignId('lead_id')->constrained('crm_leads')->cascadeOnDelete();$t->foreignId('staff_id')->nullable()->constrained('crm_staff')->nullOnDelete();$t->string('type',30);$t->string('status',30)->default('completed');$t->string('subject')->nullable();$t->text('content')->nullable();$t->string('outcome')->nullable();$t->timestamp('activity_at');$t->timestamp('next_follow_up_at')->nullable();$t->json('metadata')->nullable();$t->timestamps();$t->index(['lead_id','activity_at']);});
  Schema::create('crm_lead_distribution_events', function(Blueprint $t){$t->id();$t->foreignId('lead_id')->constrained('crm_leads')->cascadeOnDelete();$t->foreignId('from_staff_id')->nullable()->constrained('crm_staff')->nullOnDelete();$t->foreignId('to_staff_id')->nullable()->constrained('crm_staff')->nullOnDelete();$t->string('strategy',30)->nullable();$t->string('event',30);$t->string('status',30)->default('pending');$t->text('reason')->nullable();$t->foreignId('actor_user_id')->nullable()->constrained('users')->nullOnDelete();$t->timestamp('responded_at')->nullable();$t->timestamps();});
  Schema::create('crm_customers', function(Blueprint $t){$t->id();$t->string('customer_code')->unique();$t->foreignId('contact_id')->nullable()->constrained('crm_contacts')->nullOnDelete();$t->foreignId('company_id')->nullable()->constrained('crm_companies')->nullOnDelete();$t->foreignId('origin_lead_id')->nullable()->constrained('crm_leads')->nullOnDelete();$t->string('customer_type',20);$t->string('display_name');$t->string('email')->nullable()->index();$t->string('normalized_email')->nullable()->index();$t->string('phone',30)->nullable();$t->string('normalized_phone',30)->nullable()->index();$t->string('acquisition_source')->nullable()->index();$t->string('consent_status',30)->default('pending');$t->string('status',30)->default('potential')->index();$t->string('lifecycle_stage',50)->default('new_customer');$t->string('conversion_reason',50)->nullable();$t->timestamp('converted_at')->nullable();$t->foreignId('converted_by_staff_id')->nullable()->constrained('crm_staff')->nullOnDelete();$t->timestamp('first_purchase_at')->nullable();$t->timestamp('latest_purchase_at')->nullable();$t->decimal('total_revenue',18,2)->default(0);$t->string('priority',20)->default('normal');$t->timestamp('next_follow_up_at')->nullable();$t->json('metadata')->nullable();$t->timestamps();$t->softDeletes();});
  Schema::create('crm_customer_assignments', function(Blueprint $t){$t->id();$t->foreignId('customer_id')->constrained('crm_customers')->cascadeOnDelete();$t->foreignId('staff_id')->constrained('crm_staff')->cascadeOnDelete();$t->string('assignment_type',20)->default('owner');$t->string('status',20)->default('active');$t->string('reason',50)->nullable();$t->foreignId('assigned_by_user_id')->nullable()->constrained('users')->nullOnDelete();$t->timestamp('starts_at')->nullable();$t->timestamp('ends_at')->nullable();$t->timestamps();$t->index(['customer_id','status']);});
  Schema::create('crm_customer_distribution_batches', function(Blueprint $t){$t->id();$t->string('batch_code')->unique();$t->string('batch_type',30);$t->string('strategy',30);$t->string('status',30)->default('draft')->index();$t->unsignedInteger('total_items')->default(0);$t->unsignedInteger('processed_items')->default(0);$t->json('criteria')->nullable();$t->foreignId('created_by_user_id')->nullable()->constrained('users')->nullOnDelete();$t->timestamps();});
  Schema::create('crm_customer_distribution_items', function(Blueprint $t){$t->id();$t->foreignId('distribution_batch_id')->constrained('crm_customer_distribution_batches')->cascadeOnDelete();$t->foreignId('customer_id')->constrained('crm_customers')->cascadeOnDelete();$t->foreignId('original_owner_staff_id')->nullable()->constrained('crm_staff')->nullOnDelete();$t->foreignId('assigned_staff_id')->constrained('crm_staff');$t->string('assignment_type',20);$t->string('result_status',20)->default('pending');$t->string('reason')->nullable();$t->timestamps();$t->unique(['distribution_batch_id','customer_id'],'crm_dist_batch_customer_unique');});
  Schema::create('crm_customer_interactions', function(Blueprint $t){$t->id();$t->foreignId('customer_id')->constrained('crm_customers')->cascadeOnDelete();$t->foreignId('staff_id')->nullable()->constrained('crm_staff')->nullOnDelete();$t->string('interaction_type',30);$t->string('subject')->nullable();$t->text('content');$t->string('outcome')->nullable();$t->timestamp('interaction_at');$t->timestamp('next_follow_up_at')->nullable();$t->boolean('is_support_action')->default(false);$t->string('status',30)->default('completed');$t->timestamps();$t->softDeletes();});
  Schema::create('crm_audit_logs', function(Blueprint $t){$t->id();$t->string('event',100)->index();$t->string('subject_type')->nullable();$t->string('subject_id')->nullable();$t->foreignId('actor_user_id')->nullable()->constrained('users')->nullOnDelete();$t->json('changes')->nullable();$t->json('context')->nullable();$t->timestamps();$t->index(['subject_type','subject_id']);});
 }
 public function down():void { foreach(['crm_audit_logs','crm_customer_interactions','crm_customer_distribution_items','crm_customer_distribution_batches','crm_customer_assignments','crm_customers','crm_lead_distribution_events','crm_lead_activities','crm_qualification_notes','crm_contact_qualifications','crm_leads','crm_company_assignments','crm_company_match_candidates','crm_company_contacts','crm_business_contact_profiles','crm_personal_contact_profiles','crm_companies','crm_contacts','crm_staff'] as $table){Schema::dropIfExists($table);} }
};
