<?php
namespace Dth\Crm\Services;
use Dth\Crm\Models\{Lead,Staff,LeadDistributionEvent}; use Illuminate\Support\Facades\DB; use Illuminate\Validation\ValidationException; use Illuminate\Support\Collection;
final class LeadDistributionService {
 public function eligibleStaff():Collection{$today=now()->toDateString();return Staff::query()->where('employment_status','active')->whereDoesntHave('availabilities',fn($q)=>$q->where('date',$today)->whereNotIn('status',['working','remote']))->withCount(['leads as active_leads_count'=>fn($q)=>$q->whereIn('intake_status',['new','active'])])->get()->filter(fn($s)=>$s->active_leads_count<$s->lead_capacity)->values();}
 public function distribute(Lead $lead,?int $actor=null,?string $strategy=null):Lead{return DB::transaction(function()use($lead,$actor,$strategy){$strategy??=config('dth-crm.distribution.strategy','least_loaded');if($strategy==='manual')throw ValidationException::withMessages(['strategy'=>'Chiến lược thủ công yêu cầu chỉ định nhân viên cụ thể.']);$staff=$this->eligibleStaff();if($lead->company?->account_owner_staff_id){$target=$staff->firstWhere('id',$lead->company->account_owner_staff_id);if(!$target)throw ValidationException::withMessages(['staff'=>'Nhân viên phụ trách chính của doanh nghiệp hiện không sẵn sàng.']);}else{$target=$this->resolve($staff,$strategy);}if(!$target)throw ValidationException::withMessages(['staff'=>'Không có nhân viên đủ điều kiện nhận Lead.']);return $this->assign($lead,$target,$actor,$strategy);});}
 public function assign(Lead $lead,Staff $staff,?int $actor=null,string $reason='manual'):Lead{return DB::transaction(function()use($lead,$staff,$actor,$reason){if($staff->employment_status!=='active'||!$this->eligibleStaff()->contains('id',$staff->id))throw ValidationException::withMessages(['staff'=>'Nhân viên không đủ điều kiện nhận Lead.']);$from=$lead->assigned_staff_id;$lead->update(['assigned_staff_id'=>$staff->id,'assigned_at'=>now(),'assigned_by_user_id'=>$actor,'intake_status'=>'active']);$lead->qualification?->update(['assigned_staff_id'=>$staff->id,'status'=>'assigned']);LeadDistributionEvent::create(['lead_id'=>$lead->id,'from_staff_id'=>$from,'to_staff_id'=>$staff->id,'strategy'=>$reason,'event'=>'assigned','status'=>'pending','actor_user_id'=>$actor]);return $lead->fresh();});}
 public function distributeUnassigned(?string $strategy=null,?array $staffIds=null,?int $actor=null):array{$q=Lead::whereNull('assigned_staff_id')->where('intake_status','new')->orderBy('created_at')->orderBy('id');$leads=$q->get();$assigned=0;$errors=[];foreach($leads as $lead){try{$this->distribute($lead,$actor,$strategy);$assigned++;}catch(\Throwable $e){$errors[]=$lead->lead_code.': '.$e->getMessage();}}return ['assigned'=>$assigned,'skipped'=>$leads->count()-$assigned,'total'=>$leads->count(),'errors'=>$errors];}
 private function resolve(Collection $staff,string $strategy):?Staff{if($staff->isEmpty())return null;if($strategy==='round_robin'){$last=LeadDistributionEvent::where('event','assigned')->whereNotNull('to_staff_id')->latest('id')->value('to_staff_id');$ids=$staff->sortBy('id')->pluck('id')->values();$idx=$last?$ids->search($last):false;$next=$idx===false?0:(($idx+1)%$ids->count());return $staff->firstWhere('id',$ids[$next]);}if($strategy==='weighted')return $staff->sortBy(fn($s)=>($s->active_leads_count/max((float)$s->distribution_weight,0.01)).'-'.str_pad((string)$s->id,10,'0',STR_PAD_LEFT))->first();return $staff->sortBy(fn($s)=>[$s->active_leads_count,$s->id])->first();}
 public function accept(Lead $lead,int $staffId):Lead{if($lead->assigned_staff_id!==$staffId)throw ValidationException::withMessages(['lead'=>'Lead không được phân cho nhân viên này.']);LeadDistributionEvent::where('lead_id',$lead->id)->where('to_staff_id',$staffId)->where('status','pending')->latest()->first()?->update(['status'=>'accepted','event'=>'accepted','responded_at'=>now()]);return $lead;}
 public function reject(Lead $lead,int $staffId,string $reason):Lead{if($lead->assigned_staff_id!==$staffId)throw ValidationException::withMessages(['lead'=>'Lead không được phân cho nhân viên này.']);LeadDistributionEvent::where('lead_id',$lead->id)->where('to_staff_id',$staffId)->where('status','pending')->latest()->first()?->update(['status'=>'rejected','event'=>'rejected','reason'=>$reason,'responded_at'=>now()]);$lead->update(['assigned_staff_id'=>null,'assigned_at'=>null,'intake_status'=>'new']);$lead->qualification?->update(['assigned_staff_id'=>null,'status'=>'new']);return $lead;}
}
